version: '3.7'
services: 
  app: 
    container_name: app
    build: .
    ports: 
      - '1995:1995'
    environment:
      - PORT=1995
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:1.20.0-alpine
    restart: unless-stopped

